stages:
  download:
    cmd: python src/download.py
    deps:
    - src/download.py
    params:
    - download.n_locs
    - download.year
    outs:
    - data/climate_data
  prepare:
    cmd: python src/prepare.py
    deps:
    - data/climate_data
    - src/prepare.py
    outs:
    - data/List_of_Fields.npy
    - data/ground_truth.csv
  process:
    cmd: python src/process.py
    deps:
    - data/List_of_Fields.npy
    - data/climate_data
    - src/process.py
    outs:
    - data/computed_monthly_averages.csv
